include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.ast.gql.dart'
    - '**/*.req.gql.dart'
    - '**/*.data.gql.dart'
    - '**/*.var.gql.dart'
    - '**/*.gql.g.dart'
    - '**/*.gql.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
    always_use_package_imports: false
    sort_pub_dependencies: false
    depend_on_referenced_packages: false
