// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzNPDRUcwUDVDAHP0KZNXE2dUPJpn0q-c',
    appId: '1:428038298163:web:933a46f3ceeef5f4f76146',
    messagingSenderId: '428038298163',
    projectId: 'raftlabs-assignment',
    authDomain: 'raftlabs-assignment.firebaseapp.com',
    storageBucket: 'raftlabs-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdLJwnb5Djw1GXoQAwgTJAS4KW2q73XV8',
    appId: '1:428038298163:android:520285aff135232ff76146',
    messagingSenderId: '428038298163',
    projectId: 'raftlabs-assignment',
    storageBucket: 'raftlabs-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExLmQyMfReYRwjNxGoh3tbLe3xW90qfA',
    appId: '1:428038298163:ios:9d70f58175a4bdd2f76146',
    messagingSenderId: '428038298163',
    projectId: 'raftlabs-assignment',
    storageBucket: 'raftlabs-assignment.appspot.com',
    iosBundleId: 'com.yashdhrangdhariya.raftlabsAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExLmQyMfReYRwjNxGoh3tbLe3xW90qfA',
    appId: '1:428038298163:ios:5a48f963dfb5d3e9f76146',
    messagingSenderId: '428038298163',
    projectId: 'raftlabs-assignment',
    storageBucket: 'raftlabs-assignment.appspot.com',
    iosBundleId: 'com.yashdhrangdhariya.raftlabsAssignment.RunnerTests',
  );
}
